### ISSUE TITLE
Fails to detect JSON file if UTF-8 with BOM

### ISSUE THREAD

**Issue by bdbvb** [happytal/substitute-variables#14]
The task fails to parse a JSON file with encoding "UTF-8 with BOM":

`File could not be parsed as JSON: Unexpected token ﻿ in JSON at position 0`

Visual Studio (apparently) uses the "UTF-8 with BOM" encoding by default; the BOM is at the beginning of the file, and the task doesn't like it.

I can probably work around the issue by removing the BOM myself (changing the file encoding), but it would be nice if the tool could just ignore it.

If anything, maybe this info will help someone else with the same issue (check your file encoding!).

**Comment by fhervieux** [comment]
Thanks for reporting this issue! The task is now handling this case by removing the BOM before parsing and adding it back afterwards just in case. I just published version 1.2.3 on Azure DevOps with this fix.
