### ISSUE TITLE
File transfor issue in YAML if there is a "-" in key 

### ISSUE THREAD

**Issue by ajaypelluri555** [happytal/substitute-variables#20]
this was not working
  datasource:
    database-secret-key: common-db-key

Please provide the fix or provide me the code chage.If possible

**Comment by ajaypelluri555** [comment]
Sure I will try and let you know. Thank you.

**Comment by ajaypelluri555** [comment]
I tryed in datasource["database-secret-key"] syntax but it was not working.I updated in azure variable group 
spring.datasource["database-secret-key"] insted of spring.datasource.database-secret-key FYI.

Please let me know what I did is correct or do I need to change any thing.

**Comment by fhervieux** [comment]
Great!
